### ISSUE TITLE
添加「2022 年 3 月 17 日食堂问题」

### ISSUE THREAD

**Issue by mai1202** [deshengstudents/deshengstudents.com#2]
2022 年 3 月 17 日 17:30，我和另一位同学在二楼食堂吃饭。

那位同学点了「牙签肉」，据他描述，其中一块牙签肉有一股腐烂的味道。

我吃的饭菜中含土豆丝，部分土豆丝仍存在没削干净皮或发黑的情况。

**Comment by deshengstudents** [comment]
OK，已经收到问题。我们将会在近期添加一个“作恶列表”

**Comment by mai1202** [comment]
> OK，已经收到问题。我们将会在近期添加一个“作恶列表”

回的这么快？？？NB 噢

**Comment by mai1202** [comment]
> 回的这么快？？？NB 噢

哈哈，我最近比较闲。
